# Generated by Django 4.0.5 on 2022-06-15 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_company_country_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobposting', to='employment.company', verbose_name='회사_id'),
        ),
    ]
