# Generated by Django 4.0.5 on 2022-06-15 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0004_remove_company_created_at_remove_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_user', to=settings.AUTH_USER_MODEL, verbose_name='지원자'),
        ),
    ]
