# Generated by Django 4.0.5 on 2022-06-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_alter_applicationstatus_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationstatus',
            old_name='jobposting',
            new_name='jobposting_status',
        ),
    ]
